### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'static_files'

### ISSUE THREAD

**Issue by crapthings** [micnic/recache#2]
what is the first arg used for ?

i point it to my file folder and i've got this error

```
import recache from 'recache'

const fsdb = recache('../.fsdb')

console.log(fsdb.read())


=> Exited with code: 1
I20160926-15:47:09.718(8)? null
W20160926-15:47:09.726(8)? (STDERR) events.js:141
W20160926-15:47:09.727(8)? (STDERR)       throw er; // Unhandled 'error' event
W20160926-15:47:09.727(8)? (STDERR)       ^
W20160926-15:47:09.727(8)? (STDERR)
W20160926-15:47:09.727(8)? (STDERR) Error: ENOENT: no such file or directory, stat '../.fsdb'
W20160926-15:47:09.727(8)? (STDERR)     at Error (native)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by micnic** [comment]
In the first argument the path to the cached directory or file is defined

In your case there is no file or directory defined in the path `../.fsdb`, you should check the directory if everything is ok.

To catch the errors you can use:

``` js
fsdb.on('error', (error) => {
  console.log(error.stack);
});
```

also start reading the cache when it is ready, because all the data is cached asynchronously:

``` js
fsdb.on('ready', (cache) => {
  // cache.list();
  // cache.read();
});
```

**Comment by micnic** [comment]
I updated recache to version `0.4.2`, I found some bugs in last `0.4.x` versions which could throw the error you reported, please check it out
